### ISSUE TITLE
child_added in firebase not working with geofire reference in Real time database

### ISSUE THREAD

**Issue by jackphuongvu** [firebase/geofire-js#176] opened 2018-09-28 04:56 UTC
### Version info

I think there is a problem with index rule of Firebase ref because it worked well with other reference however it just didn't work with this ref from `geoFirejs`

**Firebase:**
`3.6.9`
**GeoFire:**
`4.1.2`
**Other (e.g. Node, browser, operating system) (if applicable):**

### Steps to reproduce
```
const onChildChange = (data) => {
      const position = data.val();
      console.log('geofire with Firebase');
    }

firebase.database().ref('geofire').limitToLast(1).on('child_added', onChildChange);
```
This is my code inside componentDidMount from my React Native project

- For now. this function was not be called after a new item added to Firebase database
- `ref('geofire')` is the reference geofire in the local app as well
![image](https://user-images.githubusercontent.com/23715737/46188872-df20d300-c315-11e8-8651-6b7e268715b7.png)
This is my Firebase database.

### Expected behavior
- `onChildChange` should be called each time new item has been created on Firebase server

### Actual behavior
- There is nothing log out in `console.log` right now. 
- A new item has been created well.

**Comment by puf** [comment] 2021-02-17 19:38
My first guess is that the node you add is not added to the end of the list, so it doesn't match the `.limitToLast(1)` condition in your query. GeoFire sets a `.priority` value on each node, which affects how nodes are ordered. I'd highly recommend only accessing the `geofire` node though the geofire-js API.

Given how long this issue has been open, I'm going to close it. If the problem is still relevant to you, please post a full [MCVE](http://stackoverflow.com/help/mcve) with which we can reproduce the problem.

**Closed by puf** 2021-02-17 19:38 UTC
Labels: type: bug
