### ISSUE TITLE
Error 'keyOrLocations must be a string or a mapping of key' for valid lon/lat

### ISSUE THREAD

**Issue by sarykemmoun** [firebase/geofire-js#167] opened 2018-01-10 10:50 UTC
Hello.
First, thanks for the amazing library!

### Version info

**Firebase-admin: 4.1.2**

**GeoFire: 4.1.2**

### Actual behavior

Sometimes I get this error: 'keyOrLocations must be a string or a mapping of key - location pairs'

### My code is
`      const geofireRef = new geofire(admin.database().ref('profilesLocation'));
      geofireRef.set(uid, lonLat)
        .then(() => {
          console.log('geofire finished well');
          admin.database().ref(`XXXX/${uid}`).set(XXX);
        })
`
I've ensured that I send a valid lonLat and a valid user, but somtimes I get the log 'geofire finished well' and some times the above error.

Do you have any solution for it?
Thanks in advance...

**Comment by puf** [comment] 2021-02-17 19:22
My best guess is that `uid` is `null` or `undefined` when the error occurs. You might want to check your code for that condition.

Closing the issue, because I expect you've moved on. If you still have the issue though, and the above comment doesn't help you fix it, can you provide an [MCVE](http://stackoverflow.com/help/mcve) with which we can consistently reproduce it?

**Closed by puf** 2021-02-17 19:22 UTC
Labels: type: bug
